### ISSUE TITLE
This repository is in violation of Unity Asset Store's terms.

### ISSUE THREAD

**Issue by EnoxSoftware** [aiko33/SubwayStation#1]
Hi.
I am a developer of "OpenCVForUnity".
Your public repository contains the files of the paid Unity asset that I am selling in the asset store.
Could you add the "OpenCVForUnity" folder to the .ignore file or change the attribute of the repository to private?
I hope that you will understand.
Thank you in advance.

Enox Software

**Comment by Diephen** [comment]
Hi,

Thank you for your notice and we are very sorry about this issue.
The asset has been removed from the public repo.
Sorry again for all the troubles!

**Comment by EnoxSoftware** [comment]
Thank you for your quick and polite response.

**Comment by EnoxSoftware** [comment]
Hi Diephen.

Thank you for your quick response the other day.
I noticed that the asset files remained included in past commits in your repository.
Could you delete the files completely using the "git filter - branch" command, etc?

Thank you in advance.

Enox Software
